# Generated by Django 3.2.7 on 2022-02-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
