# Generated by Django 3.1.7 on 2021-03-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcatid', models.AutoField(primary_key=True, serialize=False)),
                ('catnm', models.CharField(max_length=100)),
                ('subcatnm', models.CharField(max_length=100, unique=True)),
                ('subcaticonname', models.CharField(max_length=1000)),
            ],
        ),
    ]
